export const companies = [
  {
    name: "Salesforce",
    industry: "CRM",
    logo: "https://logo.clearbit.com/salesforce.com",
    url: "https://salesforce.com",
    description: "World's #1 CRM platform with extensive sales and marketing opportunities",
  },
  {
    name: "Gong",
    industry: "Sales Intelligence",
    logo: "https://logo.clearbit.com/gong.io",
    url: "https://gong.io",
    description: "Revenue intelligence platform transforming how sales teams work",
  },
  {
    name: "Vanta",
    industry: "Security",
    logo: "https://logo.clearbit.com/vanta.com",
    url: "https://vanta.com",
    description: "Automated security and compliance platform with growing sales team",
  },
  {
    name: "Rippling",
    industry: "HR Tech",
    logo: "https://logo.clearbit.com/rippling.com",
    url: "https://rippling.com",
    description: "All-in-one HR platform with aggressive sales expansion",
  },
  {
    name: "Okta",
    industry: "Identity",
    logo: "https://logo.clearbit.com/okta.com",
    url: "https://okta.com",
    description: "Leading identity and access management with enterprise sales focus",
  },
  {
    name: "Shopify",
    industry: "Ecommerce",
    logo: "https://logo.clearbit.com/shopify.com",
    url: "https://shopify.com",
    description: "Global commerce platform with extensive merchant success roles",
  },
  {
    name: "Glean",
    industry: "AI Search",
    logo: "https://logo.clearbit.com/glean.com",
    url: "https://glean.com",
    description: "AI-powered workplace search with rapidly growing sales team",
  },
  {
    name: "Ramp",
    industry: "Finance",
    logo: "https://logo.clearbit.com/ramp.com",
    url: "https://ramp.com",
    description: "Corporate card and spend management with high-growth sales org",
  },
  {
    name: "Brex",
    industry: "Finance",
    logo: "https://logo.clearbit.com/brex.com",
    url: "https://brex.com",
    description: "Financial services for startups with expanding sales opportunities",
  },
  {
    name: "ShipBob",
    industry: "Logistics",
    logo: "https://logo.clearbit.com/shipbob.com",
    url: "https://shipbob.com",
    description: "Ecommerce fulfillment with growing merchant acquisition team",
  },
  {
    name: "Coinbase",
    industry: "Crypto",
    logo: "https://logo.clearbit.com/coinbase.com",
    url: "https://coinbase.com",
    description: "Leading cryptocurrency exchange with institutional sales focus",
  },
  {
    name: "Stripe",
    industry: "Payments",
    logo: "https://logo.clearbit.com/stripe.com",
    url: "https://stripe.com",
    description: "Payment infrastructure with world-class sales and partnerships team",
  },
  {
    name: "Databricks",
    industry: "Data",
    logo: "https://logo.clearbit.com/databricks.com",
    url: "https://databricks.com",
    description: "Data and AI platform with enterprise sales opportunities",
  },
  {
    name: "ZoomInfo",
    industry: "Sales Intelligence",
    logo: "https://logo.clearbit.com/zoominfo.com",
    url: "https://zoominfo.com",
    description: "B2B contact database with extensive sales development roles",
  },
  {
    name: "Gusto",
    industry: "Payroll",
    logo: "https://logo.clearbit.com/gusto.com",
    url: "https://gusto.com",
    description: "Modern payroll and HR platform with growing sales team",
  },
  {
    name: "Oracle",
    industry: "Enterprise",
    logo: "https://logo.clearbit.com/oracle.com",
    url: "https://oracle.com",
    description: "Enterprise software giant with extensive sales and marketing roles",
  },
]
